USE [KmpIgreDBModel]
GO

/****** Object:  Index [NonClusteredIndex-20210602-224029]    Script Date: 6/2/2021 10:46:31 PM ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210602-224029] ON [dbo].[KompanijaZaIgreNaSrecus]
(
	[IdKmp] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


