//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Igra
    {
        public int OnlineIgraNaSrecuIdIgre { get; set; }
        public int KlijentIdKlijenta { get; set; }
    
        public virtual OnlineIgraNaSrecu OnlineIgraNaSrecu { get; set; }
        public virtual Klijent Klijent { get; set; }
    }
}
