//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KmpIgreDBModelContext : DbContext
    {
        public KmpIgreDBModelContext()
            : base("name=KmpIgreDBModelContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KompanijaZaIgreNaSrecu> KompanijaZaIgreNaSrecus { get; set; }
        public virtual DbSet<Poslovnica> Poslovnicas { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<OnlineSajt> OnlineSajts { get; set; }
        public virtual DbSet<PrenosSportskogDogadjaja> PrenosSportskogDogadjajas { get; set; }
        public virtual DbSet<OnlineIgraNaSrecu> OnlineIgraNaSrecus { get; set; }
        public virtual DbSet<Klijent> Klijents { get; set; }
        public virtual DbSet<Gleda> Gledas { get; set; }
        public virtual DbSet<Igra> Igras { get; set; }
        public virtual DbSet<Tiket> Tikets { get; set; }
        public virtual DbSet<Stampa> Stampas { get; set; }
    }
}
