//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KompanijaZaIgreNaSrecu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KompanijaZaIgreNaSrecu()
        {
            this.Poslovnicas = new HashSet<Poslovnica>();
            this.OnlineSajts = new HashSet<OnlineSajt>();
        }
    
        public int IdKmp { get; set; }
        public string NazKmp { get; set; }
        public string AdrKmp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poslovnica> Poslovnicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineSajt> OnlineSajts { get; set; }
    }
}
