//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineSajt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineSajt()
        {
            this.PrenosSportskogDogadjajas = new HashSet<PrenosSportskogDogadjaja>();
            this.OnlineIgraNaSrecus = new HashSet<OnlineIgraNaSrecu>();
        }
    
        public int IdSajta { get; set; }
        public string Domen { get; set; }
        public int KompanijaZaIgreNaSrecuIdKmp { get; set; }
        public string NazSajta { get; set; }
    
        public virtual KompanijaZaIgreNaSrecu KompanijaZaIgreNaSrecu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrenosSportskogDogadjaja> PrenosSportskogDogadjajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineIgraNaSrecu> OnlineIgraNaSrecus { get; set; }
    }
}
