//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineIgraNaSrecu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnlineIgraNaSrecu()
        {
            this.Igras = new HashSet<Igra>();
        }
    
        public int IdIgre { get; set; }
        public int OnlineSajtIdSajta { get; set; }
        public int OnlineSajtKompanijaZaIgreNaSrecuIdKmp { get; set; }
        public string NazIgre { get; set; }
    
        public virtual OnlineSajt OnlineSajt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Igra> Igras { get; set; }
    }
}
