//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poslovnica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poslovnica()
        {
            this.Radniks = new HashSet<Radnik>();
        }
    
        public int IdPosl { get; set; }
        public string Lokacija { get; set; }
        public int KompanijaZaIgreNaSrecuIdKmp { get; set; }
        public string NazPoslovnice { get; set; }
    
        public virtual KompanijaZaIgreNaSrecu KompanijaZaIgreNaSrecu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Radnik> Radniks { get; set; }
    }
}
