//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tiket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tiket()
        {
            this.Stampas = new HashSet<Stampa>();
        }
    
        public int SifraTiket { get; set; }
        public int BrParova { get; set; }
        public Nullable<int> KlijentIdKlijenta { get; set; }
    
        public virtual Klijent Klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stampa> Stampas { get; set; }
    }
}
